#!/usr/bin/env bash
source $(dirname $0)/functions.inc

function testVanilla() {
  __run "   blah"
  assertEquals "when string starts with whitespace"   "fea1"  "$(__stdout_md5)"

  __run --unknown "blah"
  assertEquals "print unsupported string"             "0dbe"  "$(__stdout_md5)"

  __run --I "inline    extra whitespace"
  assertEquals "inline with extra whitespace"         "fee7"  "$(__stdout_md5)"

}

function testDoublespace() {
  __run --right --doublespace "blah"
  assertEquals "should not end in space"              "1e2a"  "$(__stdout_md5)"

  __run --margin=40 --doublespace "blah"
  assertEquals "with a margin"                        "5110"  "$(__stdout_md5)"
}

function testQuoting() {
  __run --inline "{B_green}green{B_red} now it's red"
  assertEquals  "should not crap out with a single quote" "f87b" "$(__stdout_md5)"

  __run --inline "{B_green}green{B_red} now it\"s red"
  assertEquals  "should not crap out with a double quote" "e804" "$(__stdout_md5)"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
