#!/usr/bin/env bash
source $(dirname $0)/functions.inc

function testSwitches() {
  __run
  assertEquals "no_arguments exit status"   "0"                 "$status"
  assertEquals "no_arguments stdout_md5"    "aba4"              "$(__stdout_md5)"

  __run --help
  assertEquals "help exit status"           "0"                 "$status"
  assertEquals "help stdout"                "DESCRIPTION:"      "$(__stdout | head -n1)"

  __run --version
  assertEquals "version stdout"             "0"                 "$(__stdout | grep -c -E '^v[0-9]+\.[0-9\.]+$' &> /dev/null; echo $?)"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
