#!/usr/bin/env bash
source $(dirname $0)/functions.inc

function testVanilla() {
  __run "   blah"
  assertEquals "when string starts with whitespace"   "fea1"  "$(__stdout_md5)"

  __run --unknown "blah"
  assertEquals "print unsupported string"             "0dbe"  "$(__stdout_md5)"

  __run --inline "inline    extra whitespace"
  assertEquals "inline with extra whitespace"         "b6d4"  "$(__stdout_md5)"
}

function testInline() {
  __run --inline "{B_green}green{B_red} now it's red"
  assertEquals  "should not crap out with a single quote" "f87b" "$(__stdout_md5)"

  __run --inline "{B_green}green{B_red} now it\"s red"
  assertEquals  "should not crap out with a double quote" "e804" "$(__stdout_md5)"

  __run --inline "{       }empty"
  assertEquals  "should remote empty blocks"              "0b7f" "$(__stdout_md5)"

  __run --inline --centre "{F_red}blah"
  assertEquals  "should centre text"                      "1a44" "$(__stdout_md5)"
}

function testMultiLine() {
  __run --centre "blah\nblah"
  assertEquals  "both lines should be centred."           "1a44" "$(__stdout_md5)"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
