#!/usr/bin/env bash

dir=$(dirname $0)
tmpfile=$(mktemp -t cecho.XXX)

colours=true
for arg in $@; do
  [[ "$arg" == "--no256" ]] && colours=false
done

for test in ${dir}/test_*; do
  [[ "${test}" == './test_256' ]] && ! ${colours} && continue

  echo -n ${test}
  ./${test} &> ${tmpfile}
  if [[ $? -eq 0 ]]; then
    echo " ok"
  else
    cat ${tmpfile}
    exit 1
  fi
done

rm $tmpfile
