#!/usr/bin/env bash
source $(dirname $0)/functions.inc

function test256Colours() {
  assertEquals "when --foreground=234" "b7d8" "$(__run --foreground=234 "blah"; __stdout_md5)"
  assertEquals "when --dark-blue"      "c3da" "$(__run --dark-blue "blah"; __stdout_md5)"
  assertEquals "when --dark-gray"      "a0b8" "$(__run --dark-gray "blah"; __stdout_md5)"
  assertEquals "when --dark-green"     "4bdd" "$(__run --dark-green "blah"; __stdout_md5)"
  assertEquals "when --dark-grey"      "a0b8" "$(__run --dark-grey "blah"; __stdout_md5)"
  assertEquals "when --light-blue"     "2e10" "$(__run --light-blue "blah"; __stdout_md5)"
  assertEquals "when --light-cyan"     "4539" "$(__run --light-cyan "blah"; __stdout_md5)"
  assertEquals "when --light-green"    "f553" "$(__run --light-green "blah"; __stdout_md5)"
  assertEquals "when --light-magenta"  "2c12" "$(__run --light-magenta "blah"; __stdout_md5)"
  assertEquals "when --light-red"      "2098" "$(__run --light-red "blah"; __stdout_md5)"
  assertEquals "when --light-yellow"   "6ab4" "$(__run --light-yellow "blah"; __stdout_md5)"
  assertEquals "when --white"          "7f71" "$(__run --white "blah"; __stdout_md5)"
}


# BROKEN TESTS
# ./cecho --right --margin-right=79 "blah blah blah blahsoei soeifj osei josei "

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
